/* ============================================================
   LearnJS — dashboard.js (pages/dashboard)
   The authenticated dashboard: auth guard, project index loaded
   from Website/data/projects.json (generated by scan-projects.js),
   per-user progress tracking, filters, stats, profile and settings.
   The project grid re-renders automatically when the index file
   changes (polled) — new projects appear without manual editing.
   Loaded as a module so it can import the Firebase modules.
   ============================================================ */

import { auth } from "../../js/firebase/firebase.js";
import { db } from "../../js/firebase/firestore.js";
import { loadProjects } from "../../js/projects/project-loader.js";
import { requireAuth } from "../../js/common/require-auth.js";
import { setProjectProgress as persistProgress } from "../../js/projects/progress.js";
import {
  collection,
  query,
  getDoc,
  setDoc,
  doc,
  onSnapshot,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import {
  signOut,
  updateProfile
} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";

/* ------------------------------------------------------------
   Tiny helpers
   ------------------------------------------------------------ */
function toast(message, type) {
  if (window.LearnJS && window.LearnJS.toast) window.LearnJS.toast(message, type);
}
function el(id) { return document.getElementById(id); }
function initials(name) {
  const clean = (name || "U").trim().split(/\s+/);
  const first = (clean[0] || "").charAt(0);
  const last = clean.length > 1 ? clean[clean.length - 1].charAt(0) : "";
  return (first + last).toUpperCase() || "U";
}
function escapeHtml(value) {
  const div = document.createElement("div");
  div.textContent = value == null ? "" : String(value);
  return div.innerHTML;
}
function parseHours(estimatedTime) {
  const m = /(\d+(?:\.\d+)?)/.exec(estimatedTime || "");
  return m ? parseFloat(m[1]) : 0;
}

const CATEGORY_EMOJI = {
  "Core JS": "\u26a1", "APIs & Data": "\ud83c\udf10", "Advanced": "\ud83d\ude80",
  "Full-Stack": "\ud83e\udde9", "Games": "\ud83c\udfae"
};
const ACHIEVEMENTS = [
  { id: "first", emoji: "\ud83c\udf31", name: "First Project", desc: "Complete your first project", test: (s) => s.completed >= 1 },
  { id: "three", emoji: "\ud83d\udd25", name: "On Fire", desc: "Complete 3 projects", test: (s) => s.completed >= 3 },
  { id: "five", emoji: "\ud83c\udfc6", name: "Project Pro", desc: "Complete 5 projects", test: (s) => s.completed >= 5 },
  { id: "streak3", emoji: "\u26a1", name: "Streak 3", desc: "Reach a 3-day streak", test: (s) => s.streak >= 3 },
  { id: "ten", emoji: "\ud83d\ude80", name: "Marathoner", desc: "Complete 10 projects", test: (s) => s.completed >= 10 },
  { id: "beginner", emoji: "\ud83c\udf93", name: "Beginner Slayer", desc: "Finish every Beginner project", test: (s) => s.beginnerDone }
];

/* ------------------------------------------------------------
   State
   ------------------------------------------------------------ */
let currentUser = null;
let allProjects = [];       // raw list from Website/data/projects.json
let progressMap = {};       // slug -> { status, percent, updatedAt }
let userDoc = null;         // Firestore users/{uid} document data
let activePanel = "home";   // currently visible panel (used by topbar search jump)
let stats = { total: 0, completed: 0, started: 0, streak: 0, roadmaps: 0, hours: 0, overall: 0, beginnerDone: false };
let lastSignature = "";     // project list signature, used by the auto-refresh poll

/* ------------------------------------------------------------
   Auth guard + boot
   ------------------------------------------------------------ */
async function init() {
  const user = await requireAuth("../dashboard/");
  currentUser = user;
  document.body.classList.add("authenticated");
  el("homeUserName").textContent = user.displayName ? user.displayName.split(" ")[0] : "Learner";
  el("dashAvatarSpan").textContent = initials(user.displayName || user.email || "U");
  el("profileAvatar").textContent = initials(user.displayName || user.email || "U");
  el("profileName").textContent = user.displayName || "Learner";
  el("profileEmail").textContent = user.email || "";
  el("profileMemberSince").textContent = formatDate(user.metadata && user.metadata.creationTime);

  boot();
}
init();

async function boot() {
  // Load the generated project index (Website/data/projects.json).
  await refreshProjectList();
  // Poll so newly added project folders appear without a manual reload
  // (scan-projects.js --watch regenerates projects.json on change).
  startAutoRefresh();

  // User profile document (created lazily).
  await loadUserDoc();

  // Realtime progress per user (Firestore — preserved as-is).
  try {
    const progQuery = query(collection(db, "users", currentUser.uid, "progress"));
    onSnapshot(progQuery, (snap) => {
      progressMap = {};
      snap.docs.forEach((d) => {
        progressMap[d.id] = { id: d.id, ...d.data() };
      });
      renderAll();
    });
  } catch (err) {
    console.warn("[LearnJS] Progress listener error:", err.message);
  }
}

/** Fetch the project list and re-render only when it actually changed. */
async function refreshProjectList() {
  try {
    const list = await loadProjects();
    // Include content fields so edits to project.json (description, cover,
    // time, tags) refresh the already-open dashboard too.
    const signature = list.map((p) =>
      [p.id, p.order, p.title, p.description, p.coverImage, p.estimatedTime, (p.tags || []).join(",")].join("|")
    ).join(";");
    if (signature === lastSignature) return;
    lastSignature = signature;
    allProjects = list;
    renderAll();
  } catch (err) {
    console.warn("[LearnJS] Could not load projects:", err.message);
    const loading = el("projectsLoading");
    if (loading) loading.innerHTML = "Could not load projects. Run scan-projects.js and reload.";
  }
}

function startAutoRefresh() {
  setInterval(refreshProjectList, 20000);
  document.addEventListener("visibilitychange", () => {
    if (!document.hidden) refreshProjectList();
  });
}

async function loadUserDoc() {
  const ref = doc(db, "users", currentUser.uid);
  try {
    const snap = await getDoc(ref);
    if (snap.exists()) {
      userDoc = snap.data();
    } else {
      // Lazy-create the profile document.
      const data = {
        uid: currentUser.uid,
        displayName: currentUser.displayName || "",
        email: currentUser.email || "",
        memberSince: serverTimestamp(),
        learningHours: 0,
        currentStreak: 0,
        bestStreak: 0,
        roadmapsCompleted: [],
        createdAt: serverTimestamp()
      };
      await setDoc(ref, data);
      userDoc = data;
    }
    el("profileMemberSince").textContent =
      formatDate((userDoc.memberSince && userDoc.memberSince.toDate && userDoc.memberSince.toDate()) ||
        currentUser.metadata.creationTime);
    el("profileProjects").textContent = "0";
    el("profileRoadmaps").textContent = (userDoc.roadmapsCompleted || []).length;
  } catch (err) {
    console.warn("[LearnJS] User doc load error:", err.message);
  }
}

/* ------------------------------------------------------------
   Rendering
   ------------------------------------------------------------ */
function renderAll() {
  refreshCategories();
  computeStats();
  renderStats();
  renderProjects();
  renderRecent();
  renderActivity();
  renderAchievements();
  renderProgressBars();
  renderProfileStats();
}

function computeStats() {
  const completed = Object.values(progressMap).filter((p) => p.status === "completed");
  const started = Object.values(progressMap).filter((p) => p.status === "started");

  stats.total = allProjects.length;
  stats.completed = completed.length;
  stats.started = started.length;
  // Learning hours come from completed projects. `userDoc.learningHours` is
  // the persisted single source of truth once it's ever written, so we do NOT
  // add it on top of the recomputed sum (that would double-count).
  stats.hours = Object.keys(progressMap).reduce((sum, slug) => {
    const p = progressMap[slug];
    const project = allProjects.find((pr) => pr.id === slug);
    return sum + (p.status === "completed" && project ? parseHours(project.estimatedTime) : 0);
  }, 0);
  stats.streak = userDoc && userDoc.currentStreak ? Number(userDoc.currentStreak) : 0;
  stats.roadmaps = userDoc && userDoc.roadmapsCompleted ? userDoc.roadmapsCompleted.length : 0;
  stats.overall = stats.total ? Math.round((Object.values(progressMap).reduce((s, p) => s + (p.percent || 0), 0) / stats.total)) : 0;

  // Beginner Slayer: every Beginner project completed.
  const beginnerProjects = allProjects.filter((p) => p.difficulty === "Beginner");
  stats.beginnerDone = beginnerProjects.length > 0 &&
    beginnerProjects.every((p) => progressMap[p.id] && progressMap[p.id].status === "completed");
}

function renderStats() {
  el("statTotal").textContent = stats.total;
  el("statCompleted").textContent = stats.completed;
  el("statInProgress").textContent = stats.started;
  el("statStreak").textContent = stats.streak;
  el("statRoadmaps").textContent = stats.roadmaps;
  el("statHours").textContent = stats.hours;

  el("progCompleted").textContent = stats.completed;
  el("progStarted").textContent = stats.started;
  el("progStreak").textContent = stats.streak;
  el("progRoadmaps").textContent = stats.roadmaps;
  el("progHours").textContent = stats.hours;
  el("progOverall").textContent = stats.overall + "%";

  // Overall ring
  const ring = el("overallRing");
  if (ring) ring.style.setProperty("--pct", String(stats.overall));
  el("overallPct").textContent = stats.overall + "%";
  el("overallText").textContent =
    stats.total === 0 ? "Projects are loading\u2026" :
    stats.overall === 0 ? "Start building to grow your progress." :
    stats.overall === 100 ? "Amazing \u2014 you completed everything! \ud83c\udf89" :
    "Keep going \u2014 every project counts.";

  el("homeSummary").textContent =
    stats.completed === 0
      ? "You haven't finished a project yet \u2014 today is a great day to start."
      : "You've completed " + stats.completed + " project" + (stats.completed === 1 ? "" : "s") + ". Keep the momentum going!";
}

/* ---------- Projects grid with filters ---------- */
function currentFilters() {
  return {
    search: (el("projectSearch").value || "").trim().toLowerCase(),
    category: el("categoryFilter").value,
    difficulty: el("difficultyFilter").value,
    sort: el("sortFilter").value
  };
}

function renderProjects() {
  const grid = el("projectsGrid");
  if (!grid) return;
  const f = currentFilters();

  let list = allProjects.filter((p) => {
    if (f.category !== "all" && p.category !== f.category) return false;
    if (f.difficulty !== "all" && p.difficulty !== f.difficulty) return false;
    if (f.search) {
      const hay = (p.title + " " + (p.description || "") + " " + (p.tags || []).join(" ")).toLowerCase();
      if (hay.indexOf(f.search) === -1) return false;
    }
    return true;
  });

  switch (f.sort) {
    case "newest": list.sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0)); break;
    case "oldest": list.sort((a, b) => new Date(a.createdAt || 0) - new Date(b.createdAt || 0)); break;
    case "alpha": list.sort((a, b) => a.title.localeCompare(b.title)); break;
    case "progress": list.sort((a, b) => (progressMap[b.id] ? progressMap[b.id].percent || 0 : 0) - (progressMap[a.id] ? progressMap[a.id].percent || 0 : 0)); break;
    default: list.sort((a, b) => (a.order || 0) - (b.order || 0));
  }

  if (!allProjects.length) {
    grid.innerHTML = '<div class="dash-loading"><span class="spinner"></span> Loading projects\u2026</div>';
    return;
  }
  if (!list.length) {
    grid.innerHTML = '<div class="dash-empty">No projects match your filters.</div>';
    return;
  }

  grid.innerHTML = list.map(projectCardHTML).join("");
  // Bind card actions after render.
  grid.querySelectorAll("[data-action]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const slug = btn.getAttribute("data-slug");
      const action = btn.getAttribute("data-action");
      if (action === "start") startProject(slug);
      else if (action === "details") viewDetails(slug);
    });
  });
}

function projectCardHTML(p) {
  const prog = progressMap[p.id] || { status: "none", percent: 0 };
  const statusLabel = prog.status === "completed" ? "Done" : prog.status === "started" ? "In progress" : "";
  const statusClass = prog.status === "completed" ? "done" : prog.status === "started" ? "started" : "";
  const diffClass = (p.difficulty || "").toLowerCase();
  const emoji = CATEGORY_EMOJI[p.category] || "\ud83d\udce6";
  const timeIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>';

  return (
    '<article class="project-card">' +
      '<div class="project-cover">' +
        '<img src="' + escapeHtml(p.coverImage) + '" alt="' + escapeHtml(p.title) + '" loading="lazy">' +
        '<span class="difficulty-badge ' + diffClass + '">' + escapeHtml(p.difficulty) + "</span>" +
        (statusLabel ? '<span class="project-status ' + statusClass + '">' + statusLabel + "</span>" : "") +
      "</div>" +
      '<div class="project-body">' +
        '<h3>' + escapeHtml(p.title) + "</h3>" +
        '<p class="project-desc">' + escapeHtml(p.description) + "</p>" +
        '<div class="project-meta">' +
          '<span class="project-time">' + timeIcon + escapeHtml(p.estimatedTime) + "</span>" +
          '<span class="project-time">' + emoji + " " + escapeHtml(p.category) + "</span>" +
        "</div>" +
        '<div class="project-tags">' +
          (p.tags || []).slice(0, 3).map((t) => '<span class="tag">' + escapeHtml(t) + "</span>").join("") +
        "</div>" +
        '<div class="project-progress">' +
          '<div class="project-progress-head"><span>Progress</span><b>' + (prog.percent || 0) + "%</b></div>" +
          '<div class="bar"><div class="bar-fill" style="width:' + (prog.percent || 0) + '%"></div></div>' +
        "</div>" +
        '<div class="project-actions">' +
          '<button class="btn btn-primary btn-sm" data-action="start" data-slug="' + escapeHtml(p.id) + '" type="button">' +
            (prog.status === "completed" ? "Completed \u2713" : prog.status === "started" ? "Continue" : "Start Learning") +
          "</button>" +
          '<button class="btn btn-outline btn-sm" data-action="details" data-slug="' + escapeHtml(p.id) + '" type="button">View Details</button>' +
        "</div>" +
      "</div>" +
    "</article>"
  );
}

/* ---------- Recent projects (home) ---------- */
function renderRecent() {
  const wrap = el("homeRecent");
  if (!wrap) return;
  const recent = [...allProjects].sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0)).slice(0, 4);
  if (!recent.length) {
    wrap.innerHTML = '<div class="dash-empty">Projects will appear here.</div>';
    return;
  }
  wrap.innerHTML = recent.map((p) =>
    '<div class="recent-card">' +
      '<img src="' + escapeHtml(p.coverImage) + '" alt="' + escapeHtml(p.title) + '" loading="lazy">' +
      '<div class="recent-card-body"><h3>' + escapeHtml(p.title) + "</h3><span>" + escapeHtml(p.category) + "</span></div>" +
    "</div>"
  ).join("");
}

/* ---------- Activity feed ---------- */
function renderActivity() {
  const wrap = el("homeActivity");
  if (!wrap) return;
  const events = Object.keys(progressMap)
    .map((slug) => {
      const p = progressMap[slug];
      const project = allProjects.find((pr) => pr.id === slug);
      return project ? { project, ...p } : null;
    })
    .filter(Boolean)
    .sort((a, b) => tsMs(b.updatedAt) - tsMs(a.updatedAt))
    .slice(0, 5);

  if (!events.length) {
    wrap.innerHTML = '<div class="dash-empty">No activity yet \u2014 start a project to begin tracking.</div>';
    return;
  }
  wrap.innerHTML = events.map((e) =>
    '<div class="activity-item">' +
      '<span class="activity-dot">' + (e.status === "completed" ? "\u2705" : "\ud83d\ude80") + "</span>" +
      "<div>" +
        "<b>" + escapeHtml(e.project.title) + "</b> " +
        (e.status === "completed"
          ? '<span class="text-faint">was completed</span>'
          : '<span class="text-faint">is ' + (e.percent || 0) + "% done</span>") +
        '<p class="activity-time">' + relativeTime(e.updatedAt) + "</p>" +
      "</div>" +
    "</div>"
  ).join("");
}

/* ---------- Achievements ---------- */
function renderAchievements() {
  const wrap = el("homeAchievements");
  if (!wrap) return;
  wrap.innerHTML = ACHIEVEMENTS.map((a) => {
    const unlocked = a.test(stats);
    return (
      '<div class="ach-item' + (unlocked ? "" : " locked") + '">' +
        '<span class="ach-emoji">' + (unlocked ? a.emoji : "\ud83d\udd12") + "</span>" +
        "<div><b>" + a.name + "</b><span>" + a.desc + "</span></div>" +
      "</div>"
    );
  }).join("");
}

/* ---------- Progress bars (progress panel) ---------- */
function renderProgressBars() {
  const wrap = el("progressBars");
  if (!wrap) return;
  const rows = allProjects
    .map((p) => ({ p, prog: progressMap[p.id] || { percent: 0, status: "none" } }))
    .filter((r) => r.prog.percent > 0 || r.prog.status === "started")
    .sort((a, b) => b.prog.percent - a.prog.percent);

  if (!rows.length) {
    wrap.innerHTML = '<div class="dash-empty">Start projects to see your progress here.</div>';
    return;
  }
  wrap.innerHTML = rows.map((r) =>
    '<div class="progress-row">' +
      '<div class="progress-row-head"><b>' + escapeHtml(r.p.title) + "</b><span>" +
        (r.prog.status === "completed" ? "Completed" : r.prog.percent + "%") + "</span></div>" +
      '<div class="bar"><div class="bar-fill" style="width:' + r.prog.percent + '%"></div></div>' +
    "</div>"
  ).join("");
}

/* ---------- Profile stats ---------- */
function renderProfileStats() {
  if (el("profileProjects")) el("profileProjects").textContent = stats.completed;
  if (el("profileRoadmaps")) el("profileRoadmaps").textContent = stats.roadmaps;
}

/* ------------------------------------------------------------
   Project actions
   ------------------------------------------------------------ */
/** Persist progress and surface a toast. Shared write lives in progress.js. */
async function updateProgress(slug, status, percent) {
  if (!currentUser) return;
  const existing = progressMap[slug] || {};
  try {
    await persistProgress(currentUser.uid, slug, status, percent, existing);
    toast(status === "completed" ? "Project completed \u2014 nice work! \ud83c\udf89" : "Project started \u2014 go build it!");
  } catch (err) {
    toast("Could not save progress: " + err.message, "error");
  }
}

/** Start Learning: mark progress started, then open the project in a new tab. */
function startProject(slug) {
  const prog = progressMap[slug];
  if (prog && prog.status === "completed") return;
  const project = allProjects.find((p) => p.id === slug);
  updateProgress(slug, "started", Math.max((prog && prog.percent) || 0, 10));
  if (project && project.entryUrl) {
    window.open(project.entryUrl, "_blank", "noopener");
  } else {
    toast("This project has no entry file yet.", "error");
  }
}

/** View Details: open the (placeholder) project details page. */
function viewDetails(slug) {
  window.location.href = "../project-details/?slug=" + encodeURIComponent(slug);
}

/* ------------------------------------------------------------
   Edit profile
   ------------------------------------------------------------ */
el("editProfileBtn").addEventListener("click", () => {
  el("editName").value = currentUser.displayName || "";
  el("editModal").hidden = false;
  document.body.style.overflow = "hidden";
});
document.querySelectorAll("[data-close-edit]").forEach((btn) =>
  btn.addEventListener("click", () => { el("editModal").hidden = true; document.body.style.overflow = ""; })
);

el("editForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const name = el("editName").value.trim();
  if (name.length < 2) {
    toast("Please enter at least 2 characters.", "error");
    return;
  }
  try {
    await updateProfile(currentUser, { displayName: name });
    await setDoc(doc(db, "users", currentUser.uid), { displayName: name }, { merge: true });
    el("profileName").textContent = name;
    el("homeUserName").textContent = name.split(" ")[0];
    el("dashAvatarSpan").textContent = initials(name);
    el("profileAvatar").textContent = initials(name);
    toast("Profile updated! \u2728");
    el("editModal").hidden = true;
    document.body.style.overflow = "";
  } catch (err) {
    toast("Could not update profile: " + err.message, "error");
  }
});

/* ------------------------------------------------------------
   Navigation
   ------------------------------------------------------------ */
function goToPanel(name) {
  activePanel = name;
  document.querySelectorAll(".dash-nav-item").forEach((btn) => {
    btn.classList.toggle("active", btn.getAttribute("data-panel") === name);
  });
  document.querySelectorAll(".dash-panel").forEach((panel) => {
    panel.classList.toggle("active", panel.getAttribute("data-panel-body") === name);
  });
  closeSidebar();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

document.querySelectorAll(".dash-nav-item[data-panel]").forEach((btn) => {
  btn.addEventListener("click", () => goToPanel(btn.getAttribute("data-panel")));
});
document.querySelectorAll("[data-goto]").forEach((btn) => {
  btn.addEventListener("click", () => goToPanel(btn.getAttribute("data-goto")));
});
el("continueBtn").addEventListener("click", () => goToPanel("projects"));
el("dashAvatarBtn").addEventListener("click", () => goToPanel("profile"));

/* ---------- Sidebar (mobile) ---------- */
function closeSidebar() { document.body.classList.remove("dash-open"); el("dashMenuToggle").setAttribute("aria-expanded", "false"); }
el("dashMenuToggle").addEventListener("click", () => {
  const open = document.body.classList.toggle("dash-open");
  el("dashMenuToggle").setAttribute("aria-expanded", String(open));
});
el("dashBackdrop").addEventListener("click", closeSidebar);

// Escape closes the edit-profile modal (kept after the project modal was
// replaced by the details page).
document.addEventListener("keydown", (e) => {
  if (e.key !== "Escape") return;
  const edit = el("editModal");
  if (edit && !edit.hidden) {
    edit.hidden = true;
    document.body.style.overflow = "";
  }
});

/* ---------- Filters ---------- */
["projectSearch", "categoryFilter", "difficultyFilter", "sortFilter"].forEach((id) => {
  const node = el(id);
  if (node) node.addEventListener("input", renderProjects);
});

// Populate category options dynamically from loaded data.
let lastCategories = "";
function refreshCategories() {
  const cats = [...new Set(allProjects.map((p) => p.category).filter(Boolean))].sort();
  const key = cats.join("|");
  if (key === lastCategories) return; // skip needless DOM churn on progress updates
  lastCategories = key;
  const select = el("categoryFilter");
  if (!select) return;
  const current = select.value;
  select.innerHTML = '<option value="all">All Categories</option>' +
    cats.map((c) => '<option value="' + escapeHtml(c) + '">' + escapeHtml(c) + "</option>").join("");
  if ([...select.options].some((o) => o.value === current)) select.value = current;
}

// Topbar search also filters the projects grid — and jumps to the Projects
// panel so the results are visible. Clearing the query returns to Home.
el("dashSearch").addEventListener("input", (e) => {
  el("projectSearch").value = e.target.value;
  renderProjects();
  if (e.target.value) {
    if (activePanel !== "projects") goToPanel("projects");
  } else if (activePanel === "projects") {
    goToPanel("home");
  }
});

/* ---------- Notifications + settings ---------- */
el("dashNotify").addEventListener("click", () => {
  toast("You're all caught up \ud83d\udd14");
});

el("settingsThemeBtn").addEventListener("click", () => {
  if (window.LearnJS && window.LearnJS.theme) window.LearnJS.theme.toggle();
});

el("notifyToggle").addEventListener("change", (e) => {
  try { localStorage.setItem("learnjs-notifications", e.target.checked ? "on" : "off"); } catch (err) {}
  toast(e.target.checked ? "Notifications on." : "Notifications off.");
});

function logout() {
  signOut(auth).then(() => {
    window.location.href = "../home/";
  }).catch((err) => toast(err.message, "error"));
}
el("dashLogout").addEventListener("click", logout);
el("settingsLogoutBtn").addEventListener("click", logout);

/* ------------------------------------------------------------
   Date helpers
   ------------------------------------------------------------ */
/** Millis from a Firestore Timestamp, Date, string or undefined. */
function tsMs(value) {
  if (!value) return 0;
  if (value.toMillis) return value.toMillis();
  const d = new Date(value).getTime();
  return isNaN(d) ? 0 : d;
}

function formatDate(value) {
  if (!value) return "\u2014";
  const d = value instanceof Date ? value : new Date(value);
  if (isNaN(d.getTime())) return "\u2014";
  return d.toLocaleDateString(undefined, { month: "short", year: "numeric" });
}

function relativeTime(value) {
  if (!value) return "";
  const ms = tsMs(value);
  const diff = Date.now() - ms;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return mins + "m ago";
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return hrs + "h ago";
  const days = Math.floor(hrs / 24);
  if (days < 7) return days + "d ago";
  return new Date(ms).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}
// end of dashboard.js
