/* ============================================================
   LearnJS — dashboard.js (pages/dashboard)
   The authenticated dashboard: auth guard, project index loaded
   from Website/data/projects.json (generated by scan-projects.js),
   per-user progress tracking, filters, stats, profile and settings.
   The project grid re-renders automatically when the index file
   changes (polled) — new projects appear without manual editing.
   Loaded as a module so it can import the Firebase modules.
   ============================================================ */

import { auth } from "../../js/firebase/firebase.js";
import { db } from "../../js/firebase/firestore.js";
import { loadProjects } from "../../js/projects/project-loader.js";
import { requireAuth } from "../../js/common/require-auth.js";
import { initRoadmap, renderRoadmap } from "../../js/roadmap/roadmap.js";
import { initLearning, openTopic, flushPendingNotes } from "../../js/roadmap/learning.js";
import {
  initProgress,
  subscribe,
  subscribeSync,
  getDebugInfo,
  flushWrites,
  isDev
} from "../../js/roadmap/roadmap-progress.js";
import { setProjectProgress as persistProgress } from "../../js/projects/progress.js";
import {
  collection,
  query,
  getDoc,
  setDoc,
  doc,
  onSnapshot,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import {
  signOut,
  updateProfile
} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";

/* ------------------------------------------------------------
   Tiny helpers
   ------------------------------------------------------------ */
function toast(message, type) {
  if (window.LearnJS && window.LearnJS.toast) window.LearnJS.toast(message, type);
}
function el(id) { return document.getElementById(id); }
function initials(name) {
  const clean = (name || "U").trim().split(/\s+/);
  const first = (clean[0] || "").charAt(0);
  const last = clean.length > 1 ? clean[clean.length - 1].charAt(0) : "";
  return (first + last).toUpperCase() || "U";
}
function escapeHtml(value) {
  const div = document.createElement("div");
  div.textContent = value == null ? "" : String(value);
  return div.innerHTML;
}
function parseHours(estimatedTime) {
  const m = /(\d+(?:\.\d+)?)/.exec(estimatedTime || "");
  return m ? parseFloat(m[1]) : 0;
}

/* Lucide icon markup (https://lucide.dev) — stroke-based, matches the design system. */
const ICONS = {
  clock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>',
  check: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>',
  rocket: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"/><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09"/><path d="M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z"/><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05"/></svg>',
  play: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"/></svg>',
  arrowRight: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>',
  external: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>',
  lock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>',
  sprout: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3"/><path d="M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4"/><path d="M5 21h14"/></svg>',
  flame: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"/></svg>',
  trophy: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 14.66V17a1 1 0 0 1-1 1 2 2 0 0 0-2 2v2"/><path d="M14 14.66V17a1 1 0 0 0 1 1 2 2 0 0 1 2 2v2"/><path d="M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3"/><path d="M4 22h16"/><path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z"/><path d="M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3"/></svg>',
  zap: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15.914 4a1.5 1.5 0 0 0-2.474-1.561l-9 9A1.5 1.5 0 0 0 5.5 14h4.002a.5.5 0 0 1 .471.666L8.086 20a1.5 1.5 0 0 0 2.475 1.56l9-9A1.5 1.5 0 0 0 18.5 10h-3.997a.5.5 0 0 1-.472-.667z"/></svg>',
  graduation: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/></svg>',
  inbox: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></svg>',
  folderOpen: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"/></svg>',
  trending: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/></svg>',
  globe: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>',
  puzzle: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z"/></svg>',
  gamepad: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" x2="10" y1="11" y2="11"/><line x1="8" x2="8" y1="9" y2="13"/><line x1="15" x2="15.01" y1="12" y2="12"/><line x1="18" x2="18.01" y1="10" y2="10"/><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z"/></svg>'
};

const CATEGORY_ICON = {
  "Core JS": ICONS.zap, "APIs & Data": ICONS.globe, "Advanced": ICONS.rocket,
  "Full-Stack": ICONS.puzzle, "Games": ICONS.gamepad
};
const ACHIEVEMENTS = [
  { id: "first", icon: ICONS.sprout, name: "First Project", desc: "Complete your first project", test: (s) => s.completed >= 1 },
  { id: "three", icon: ICONS.flame, name: "On Fire", desc: "Complete 3 projects", test: (s) => s.completed >= 3 },
  { id: "five", icon: ICONS.trophy, name: "Project Pro", desc: "Complete 5 projects", test: (s) => s.completed >= 5 },
  { id: "streak3", icon: ICONS.zap, name: "Streak 3", desc: "Reach a 3-day streak", test: (s) => s.streak >= 3 },
  { id: "ten", icon: ICONS.rocket, name: "Marathoner", desc: "Complete 10 projects", test: (s) => s.completed >= 10 },
  { id: "beginner", icon: ICONS.graduation, name: "Beginner Slayer", desc: "Finish every Beginner project", test: (s) => s.beginnerDone }
];

/* ------------------------------------------------------------
   State
   ------------------------------------------------------------ */
let currentUser = null;
let allProjects = [];       // raw list from Website/data/projects.json
let progressMap = {};       // slug -> { status, percent, updatedAt }
let userDoc = null;         // Firestore users/{uid} document data
let activePanel = "home";   // currently visible panel
let stats = { total: 0, completed: 0, started: 0, streak: 0, roadmaps: 0, hours: 0, overall: 0, beginnerDone: false };
let lastSignature = "";     // project list signature, used by the auto-refresh poll

/* ------------------------------------------------------------
   Sidebar collapse (desktop) + icon-only tooltips
   ------------------------------------------------------------ */
const SIDEBAR_STORAGE_KEY = "learnjs-dash-sidebar";
const dashShell = document.getElementById("dashShell");
const dashSidebar = document.getElementById("dashSidebar");

function applySidebarState(collapsed) {
  dashShell.classList.toggle("sidebar-collapsed", collapsed);
  dashSidebar.classList.toggle("collapsed", collapsed);
  const btn = document.getElementById("dashCollapseToggle");
  if (btn) {
    btn.setAttribute("aria-pressed", String(collapsed));
    btn.setAttribute("aria-label", collapsed ? "Expand sidebar" : "Collapse sidebar");
  }
}

function initSidebarState() {
  let collapsed = false;
  try { collapsed = localStorage.getItem(SIDEBAR_STORAGE_KEY) === "collapsed"; } catch (err) {}
  applySidebarState(collapsed);
}

document.getElementById("dashCollapseToggle").addEventListener("click", () => {
  const collapsed = !dashShell.classList.contains("sidebar-collapsed");
  applySidebarState(collapsed);
  try { localStorage.setItem(SIDEBAR_STORAGE_KEY, collapsed ? "collapsed" : "expanded"); } catch (err) {}
});

/* Floating tooltip for nav items when the sidebar is collapsed. */
function initSidebarTooltips() {
  const tip = document.createElement("div");
  tip.className = "dash-tooltip";
  tip.setAttribute("role", "tooltip");
  document.body.appendChild(tip);

  document.querySelectorAll(".dash-nav-item").forEach((item) => {
    const label = item.getAttribute("data-label") || item.textContent.trim();
    item.addEventListener("mouseenter", () => {
      if (!dashSidebar.classList.contains("collapsed") || window.innerWidth <= 1024) return;
      tip.textContent = label;
      const r = item.getBoundingClientRect();
      tip.style.top = r.top + r.height / 2 + "px";
      tip.style.left = r.right + 12 + "px";
      tip.classList.add("show");
    });
    item.addEventListener("mouseleave", () => tip.classList.remove("show"));
    item.addEventListener("click", () => tip.classList.remove("show"));
  });
}

initSidebarState();
initSidebarTooltips();

/* ------------------------------------------------------------
   Auth guard + boot
   ------------------------------------------------------------ */
async function init() {
  const user = await requireAuth("../dashboard/");
  currentUser = user;
  document.body.classList.add("authenticated");
  el("homeUserName").textContent = user.displayName ? user.displayName.split(" ")[0] : "Learner";
  el("dashAvatarSpan").textContent = initials(user.displayName || user.email || "U");
  el("profileAvatar").textContent = initials(user.displayName || user.email || "U");
  el("profileName").textContent = user.displayName || "Learner";
  el("profileEmail").textContent = user.email || "";
  el("profileMemberSince").textContent = formatDate(user.metadata && user.metadata.creationTime);

  // Personal/account actions live behind the top-right avatar.
  buildAccountMenu(user);

  // Account-menu deep links from other pages (e.g. ../dashboard/#settings) and
  // the legacy interview page redirect (../dashboard/#interview).
  const targetPanel = (location.hash || "").replace(/^#/, "");
  if (targetPanel === "profile" || targetPanel === "settings" || targetPanel === "interview") {
    goToPanel(targetPanel);
    history.replaceState(null, "", location.pathname + location.search);
  }

  boot();
}
init();

async function boot() {
  // Roadmap module — the curriculum is LOCAL (data/roadmap.json + embedded
  // fallback), so the roadmap + learning panels render FIRST and never wait
  // on Firebase. Progress syncs in the background below.
  await initRoadmap();
  await initLearning();

  // Load the generated project index (Website/data/projects.json).
  await refreshProjectList();
  // Poll so newly added project folders appear without a manual reload
  // (scan-projects.js --watch regenerates projects.json on change).
  startAutoRefresh();

  // User profile document (created lazily).
  await loadUserDoc();

  // Roadmap progress — Firestore stores ONLY user-specific progress at
  // users/{uid}/roadmap (completed lessons, current lesson, notes). Started
  // after the panels render and deliberately NOT awaited: if Firestore is
  // slow or unreachable the roadmap tree still shows, and progress catches
  // up via onSnapshot the moment the connection returns. (initProgress never
  // rejects — failures are routed to its snapshot error callback.)
  initProgress(currentUser);

  // Offline banner + dev debug panel for the roadmap progress store.
  initRoadmapDiagnostics();

  // Realtime progress per user (Firestore — preserved as-is).
  try {
    const progQuery = query(collection(db, "users", currentUser.uid, "progress"));
    onSnapshot(progQuery, (snap) => {
      progressMap = {};
      snap.docs.forEach((d) => {
        progressMap[d.id] = { id: d.id, ...d.data() };
      });
      renderAll();
    });
  } catch (err) {
    console.warn("[LearnJS] Progress listener error:", err.message);
  }
}

/** Fetch the project list and re-render only when it actually changed. */
async function refreshProjectList() {
  try {
    const list = await loadProjects();
    // Include content fields so edits to project.json (description, cover,
    // time, tags) refresh the already-open dashboard too.
    const signature = list.map((p) =>
      [p.id, p.order, p.title, p.description, p.coverImage, p.estimatedTime, (p.tags || []).join(",")].join("|")
    ).join(";");
    if (signature === lastSignature) return;
    lastSignature = signature;
    allProjects = list;
    renderAll();
  } catch (err) {
    console.warn("[LearnJS] Could not load projects:", err.message);
    const loading = el("projectsLoading");
    if (loading) loading.innerHTML = "Could not load projects. Run scan-projects.js and reload.";
  }
}

function startAutoRefresh() {
  setInterval(refreshProjectList, 20000);
  document.addEventListener("visibilitychange", () => {
    if (!document.hidden) refreshProjectList();
  });
}

async function loadUserDoc() {
  const ref = doc(db, "users", currentUser.uid);
  try {
    const snap = await getDoc(ref);
    if (snap.exists()) {
      userDoc = snap.data();
    } else {
      // Lazy-create the profile document.
      const data = {
        uid: currentUser.uid,
        displayName: currentUser.displayName || "",
        email: currentUser.email || "",
        memberSince: serverTimestamp(),
        learningHours: 0,
        currentStreak: 0,
        bestStreak: 0,
        roadmapsCompleted: [],
        createdAt: serverTimestamp()
      };
      await setDoc(ref, data);
      userDoc = data;
    }
    el("profileMemberSince").textContent =
      formatDate((userDoc.memberSince && userDoc.memberSince.toDate && userDoc.memberSince.toDate()) ||
        currentUser.metadata.creationTime);
    el("profileProjects").textContent = "0";
    el("profileRoadmaps").textContent = (userDoc.roadmapsCompleted || []).length;
  } catch (err) {
    console.warn("[LearnJS] User doc load error:", err.message);
  }
}

/* ------------------------------------------------------------
   Rendering
   ------------------------------------------------------------ */
function renderAll() {
  refreshCategories();
  computeStats();
  renderStats();
  renderProjects();
  renderContinue();
  renderAchievements();
  renderProgressBars();
  renderProfileStats();
}

function computeStats() {
  const completed = Object.values(progressMap).filter((p) => p.status === "completed");
  const started = Object.values(progressMap).filter((p) => p.status === "started");

  stats.total = allProjects.length;
  stats.completed = completed.length;
  stats.started = started.length;
  // Learning hours come from completed projects. `userDoc.learningHours` is
  // the persisted single source of truth once it's ever written, so we do NOT
  // add it on top of the recomputed sum (that would double-count).
  stats.hours = Object.keys(progressMap).reduce((sum, slug) => {
    const p = progressMap[slug];
    const project = allProjects.find((pr) => pr.id === slug);
    return sum + (p.status === "completed" && project ? parseHours(project.estimatedTime) : 0);
  }, 0);
  stats.streak = userDoc && userDoc.currentStreak ? Number(userDoc.currentStreak) : 0;
  stats.roadmaps = userDoc && userDoc.roadmapsCompleted ? userDoc.roadmapsCompleted.length : 0;
  stats.overall = stats.total ? Math.round((Object.values(progressMap).reduce((s, p) => s + (p.percent || 0), 0) / stats.total)) : 0;

  // Beginner Slayer: every Beginner project completed.
  const beginnerProjects = allProjects.filter((p) => p.difficulty === "Beginner");
  stats.beginnerDone = beginnerProjects.length > 0 &&
    beginnerProjects.every((p) => progressMap[p.id] && progressMap[p.id].status === "completed");
}

function renderStats() {
  el("statTotal").textContent = stats.total;
  el("statCompleted").textContent = stats.completed;
  el("statInProgress").textContent = stats.started;

  el("progCompleted").textContent = stats.completed;
  el("progStarted").textContent = stats.started;
  el("progStreak").textContent = stats.streak;
  el("progRoadmaps").textContent = stats.roadmaps;
  el("progHours").textContent = stats.hours;
  el("progOverall").textContent = stats.overall + "%";

  // Overall ring
  const ring = el("overallRing");
  if (ring) ring.style.setProperty("--pct", String(stats.overall));
  el("overallPct").textContent = stats.overall + "%";
  el("overallText").textContent =
    stats.total === 0 ? "Projects are loading\u2026" :
    stats.overall === 0 ? "Start building to grow your progress." :
    stats.overall === 100 ? "Amazing \u2014 you completed everything! \ud83c\udf89" :
    "Keep going \u2014 every project counts.";

  // Static sub-line; the motivational pill below carries the dynamic copy.
  el("homeSummary").textContent = "Here's what's happening with your learning today.";

  // Motivational pill under the greeting — keeps the welcome engaging.
  const motive = el("homeMotive");
  if (motive) {
    const icon = stats.started > 0 ? ICONS.zap : stats.completed > 0 ? ICONS.flame : ICONS.rocket;
    const text =
      stats.started > 0
        ? stats.started + (stats.started === 1 ? " project" : " projects") + " in progress \u2014 keep it going"
        : stats.completed > 0
          ? "You're building consistently \u2014 " + stats.completed + " completed"
          : "Today's goal: start your first project";
    motive.innerHTML = icon + "<span>" + text + "</span>";
  }
}

/* ---------- Projects grid with filters ---------- */
function currentFilters() {
  return {
    search: (el("projectSearch").value || "").trim().toLowerCase(),
    category: el("categoryFilter").value,
    difficulty: el("difficultyFilter").value,
    sort: el("sortFilter").value
  };
}

function renderProjects() {
  const grid = el("projectsGrid");
  if (!grid) return;
  const f = currentFilters();

  let list = allProjects.filter((p) => {
    if (f.category !== "all" && p.category !== f.category) return false;
    if (f.difficulty !== "all" && p.difficulty !== f.difficulty) return false;
    if (f.search) {
      const hay = (p.title + " " + (p.description || "") + " " + (p.tags || []).join(" ")).toLowerCase();
      if (hay.indexOf(f.search) === -1) return false;
    }
    return true;
  });

  switch (f.sort) {
    case "newest": list.sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0)); break;
    case "oldest": list.sort((a, b) => new Date(a.createdAt || 0) - new Date(b.createdAt || 0)); break;
    case "alpha": list.sort((a, b) => a.title.localeCompare(b.title)); break;
    case "progress": list.sort((a, b) => (progressMap[b.id] ? progressMap[b.id].percent || 0 : 0) - (progressMap[a.id] ? progressMap[a.id].percent || 0 : 0)); break;
    default: list.sort((a, b) => (a.order || 0) - (b.order || 0));
  }

  if (!allProjects.length) {
    grid.innerHTML = '<div class="dash-loading"><span class="spinner"></span> Loading projects\u2026</div>';
    return;
  }
  if (!list.length) {
    grid.innerHTML = '<div class="dash-empty"><span class="empty-ico">' + ICONS.inbox + "</span>No projects match your filters.</div>";
    return;
  }

  grid.innerHTML = list.map(projectCardHTML).join("");
  bindCardActions(grid);
}

/* Shared card-action binding for any container of project cards. */
function bindCardActions(container) {
  container.querySelectorAll("[data-action]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const slug = btn.getAttribute("data-slug");
      const action = btn.getAttribute("data-action");
      if (action === "start") startProject(slug);
      else if (action === "details") viewDetails(slug);
    });
  });
}

/* Shared difficulty + status badge data for a project card. Status is driven
   by the user's live progress; difficulty by the project data field. */
function badgeParts(p) {
  const prog = progressMap[p.id] || { status: "none", percent: 0 };
  const statusLabel = prog.status === "completed" ? "Completed" : prog.status === "started" ? "In Progress" : "Not Started";
  const statusClass = prog.status === "completed" ? "done" : prog.status === "started" ? "started" : "none";
  const diffClass = (p.difficulty || "").toLowerCase();
  const diffBadge = p.difficulty ? '<span class="difficulty-badge ' + diffClass + '">' + escapeHtml(p.difficulty) + "</span>" : "";
  return { statusLabel, statusClass, diffBadge };
}

function projectCardHTML(p) {
  const prog = progressMap[p.id] || { status: "none", percent: 0 };
  const { statusLabel, statusClass, diffBadge } = badgeParts(p);
  const catIcon = CATEGORY_ICON[p.category] || ICONS.folderOpen;
  const actionIcon = prog.status === "completed" ? ICONS.check : prog.status === "started" ? ICONS.arrowRight : ICONS.play;
  const actionLabel = prog.status === "completed" ? "Completed" : prog.status === "started" ? "Continue" : "Start Learning";

  return (
    '<article class="project-card">' +
      '<div class="project-cover">' +
        '<img src="' + escapeHtml(p.coverImage) + '" alt="' + escapeHtml(p.title) + '" loading="lazy">' +
        diffBadge +
      "</div>" +
      '<div class="project-body">' +
        '<h3>' + escapeHtml(p.title) + "</h3>" +
        '<p class="project-desc">' + escapeHtml(p.description) + "</p>" +
        '<div class="project-meta">' +
          '<span class="project-time">' + ICONS.clock + escapeHtml(p.estimatedTime) + "</span>" +
          '<span class="project-time">' + catIcon + " " + escapeHtml(p.category) + "</span>" +
        "</div>" +
        '<div class="project-tags">' +
          (p.tags || []).slice(0, 3).map((t) => '<span class="tag">' + escapeHtml(t) + "</span>").join("") +
        "</div>" +
        '<div class="project-progress">' +
          '<div class="project-progress-head"><span>Progress</span><b>' + (prog.percent || 0) + "%</b></div>" +
          '<div class="bar"><div class="bar-fill" style="width:' + (prog.percent || 0) + '%"></div></div>' +
        "</div>" +
        '<div class="project-status-row">' +
          '<span class="project-status ' + statusClass + '">' + statusLabel + "</span>" +
        "</div>" +
        '<div class="project-actions">' +
          '<button class="btn btn-primary btn-sm" data-action="start" data-slug="' + escapeHtml(p.id) + '" type="button">' +
            actionIcon + actionLabel +
          "</button>" +
          '<button class="btn btn-outline btn-sm" data-action="details" data-slug="' + escapeHtml(p.id) + '" type="button">' +
            ICONS.external + "View Details" +
          "</button>" +
        "</div>" +
      "</div>" +
    "</article>"
  );
}

/* ---------- Continue learning / Your Projects (home) ----------
   Netflix-style "Continue Watching": only projects the user has actually
   touched (started, in progress, resumed, completed — anything that wrote a
   progress doc). Never-opened projects are excluded. Ordered by most recent
   activity (updatedAt) so resuming a project bumps it to the front.
   Reuses the exact project-card markup from the Projects panel. */
function renderContinue() {
  const wrap = el("homeContinue");
  if (!wrap) return;

  const active = allProjects
    .map((p) => ({ project: p, prog: progressMap[p.id] }))
    .filter((r) => r.prog &&
      (r.prog.status === "started" || r.prog.status === "completed" || (r.prog.percent || 0) > 0))
    .sort((a, b) => tsMs(b.prog.updatedAt) - tsMs(a.prog.updatedAt))
    .slice(0, 4);

  if (!active.length) {
    wrap.innerHTML =
      '<div class="dash-empty continue-empty">' +
        '<span class="empty-emoji">📚</span>' +
        "<b>No active projects yet</b>" +
        "<span>Start your first JavaScript project and it will appear here automatically.</span>" +
        '<button class="btn btn-primary btn-sm" data-action="browse" type="button">' +
          ICONS.folderOpen + "Browse Projects" +
        "</button>" +
      "</div>";
    const browse = wrap.querySelector('[data-action="browse"]');
    if (browse) browse.addEventListener("click", () => goToPanel("projects"));
    return;
  }

  wrap.innerHTML = active.map((r) => projectCardHTML(r.project)).join("");
  bindCardActions(wrap);
}

/* ---------- Achievements ---------- */
function renderAchievements() {
  const wrap = el("homeAchievements");
  if (!wrap) return;
  wrap.innerHTML = ACHIEVEMENTS.map((a) => {
    const unlocked = a.test(stats);
    return (
      '<div class="ach-item' + (unlocked ? "" : " locked") + '">' +
        '<span class="ach-emoji">' + (unlocked ? a.icon : ICONS.lock) + "</span>" +
        "<div><b>" + a.name + "</b><span>" + a.desc + "</span></div>" +
      "</div>"
    );
  }).join("");
}

/* ---------- Progress bars (progress panel) ---------- */
function renderProgressBars() {
  const wrap = el("progressBars");
  if (!wrap) return;
  const rows = allProjects
    .map((p) => ({ p, prog: progressMap[p.id] || { percent: 0, status: "none" } }))
    .filter((r) => r.prog.percent > 0 || r.prog.status === "started")
    .sort((a, b) => b.prog.percent - a.prog.percent);

  if (!rows.length) {
    wrap.innerHTML = '<div class="dash-empty"><span class="empty-ico">' + ICONS.trending + "</span>Start projects to see your progress here.</div>";
    return;
  }
  wrap.innerHTML = rows.map((r) =>
    '<div class="progress-row">' +
      '<div class="progress-row-head"><b>' + escapeHtml(r.p.title) + "</b><span>" +
        (r.prog.status === "completed" ? "Completed" : r.prog.percent + "%") + "</span></div>" +
      '<div class="bar"><div class="bar-fill" style="width:' + r.prog.percent + '%"></div></div>' +
    "</div>"
  ).join("");
}

/* ---------- Profile stats ---------- */
function renderProfileStats() {
  if (el("profileProjects")) el("profileProjects").textContent = stats.completed;
  if (el("profileRoadmaps")) el("profileRoadmaps").textContent = stats.roadmaps;
}

/* ------------------------------------------------------------
   Project actions
   ------------------------------------------------------------ */
/** Persist progress and surface a toast. Shared write lives in progress.js. */
async function updateProgress(slug, status, percent) {
  if (!currentUser) return;
  const existing = progressMap[slug] || {};
  try {
    await persistProgress(currentUser.uid, slug, status, percent, existing);
    toast(status === "completed" ? "Project completed \u2014 nice work! \ud83c\udf89" : "Project started \u2014 go build it!");
  } catch (err) {
    toast("Could not save progress: " + err.message, "error");
  }
}

/** Start Learning: mark progress started, then open the project in a new tab. */
function startProject(slug) {
  const prog = progressMap[slug];
  if (prog && prog.status === "completed") return;
  const project = allProjects.find((p) => p.id === slug);
  updateProgress(slug, "started", Math.max((prog && prog.percent) || 0, 10));
  if (project && project.entryUrl) {
    window.open(project.entryUrl, "_blank", "noopener");
  } else {
    toast("This project has no entry file yet.", "error");
  }
}

/** View Details: open the (placeholder) project details page. Also bumps the
    project's updatedAt (for projects the user has already touched) so opening
    / resuming a project re-orders it to the front of Continue Learning.
    Fire-and-forget: the write is a cosmetic re-order, so navigation never
    waits on it. Status is guarded — docs with percent>0 but no status field
    would otherwise make Firestore reject the write (undefined field value). */
function viewDetails(slug) {
  const prog = progressMap[slug];
  if (prog && prog.status && currentUser) {
    persistProgress(currentUser.uid, slug, prog.status, prog.percent || 0, prog)
      .catch(() => { /* non-fatal — opening the details page must never block */ });
  }
  window.location.href = "../project-details/?slug=" + encodeURIComponent(slug);
}

/* ------------------------------------------------------------
   Edit profile
   ------------------------------------------------------------ */
el("editProfileBtn").addEventListener("click", () => {
  el("editName").value = currentUser.displayName || "";
  el("editModal").hidden = false;
  document.body.style.overflow = "hidden";
});
document.querySelectorAll("[data-close-edit]").forEach((btn) =>
  btn.addEventListener("click", () => { el("editModal").hidden = true; document.body.style.overflow = ""; })
);

el("editForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const name = el("editName").value.trim();
  if (name.length < 2) {
    toast("Please enter at least 2 characters.", "error");
    return;
  }
  try {
    await updateProfile(currentUser, { displayName: name });
    await setDoc(doc(db, "users", currentUser.uid), { displayName: name }, { merge: true });
    el("profileName").textContent = name;
    el("homeUserName").textContent = name.split(" ")[0];
    el("dashAvatarSpan").textContent = initials(name);
    el("profileAvatar").textContent = initials(name);
    // Keep the account-menu header in sync with the new display name.
    if (dashAccountMenu) {
      const headName = dashAccountMenu.querySelector(".avatar-menu-name");
      if (headName) headName.textContent = name;
      const headAvatar = dashAccountMenu.querySelector(".avatar-menu-head .avatar");
      if (headAvatar) headAvatar.textContent = initials(name);
    }
    toast("Profile updated! \u2728");
    el("editModal").hidden = true;
    document.body.style.overflow = "";
  } catch (err) {
    toast("Could not update profile: " + err.message, "error");
  }
});

/* ------------------------------------------------------------
   Navigation
   ------------------------------------------------------------ */
function goToPanel(name) {
  activePanel = name;
  document.querySelectorAll(".dash-nav-item").forEach((btn) => {
    // The Learning page belongs to the Roadmap flow — keep Roadmap highlighted.
    const target = name === "learning" ? "roadmap" : name;
    btn.classList.toggle("active", btn.getAttribute("data-panel") === target);
  });
  document.querySelectorAll(".dash-panel").forEach((panel) => {
    panel.classList.toggle("active", panel.getAttribute("data-panel-body") === name);
  });
  // Roadmap + Learning maximize the content area — collapse the sidebar for
  // the learning flow only. The user's stored preference is restored when
  // leaving, so the rest of the dashboard keeps its usual look.
  if (name === "roadmap" || name === "learning") {
    if (!dashShell.classList.contains("sidebar-collapsed")) applySidebarState(true);
  } else if (dashShell.classList.contains("sidebar-collapsed")) {
    let saved = false;
    try { saved = localStorage.getItem(SIDEBAR_STORAGE_KEY) === "collapsed"; } catch (err) {}
    if (!saved) applySidebarState(false);
  }
  // Refresh live progress every time the roadmap panel is opened.
  if (name === "roadmap") renderRoadmap();
  closeSidebar();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

document.querySelectorAll(".dash-nav-item[data-panel]").forEach((btn) => {
  btn.addEventListener("click", () => goToPanel(btn.getAttribute("data-panel")));
});
document.querySelectorAll("[data-goto]").forEach((btn) => {
  btn.addEventListener("click", () => goToPanel(btn.getAttribute("data-goto")));
});
el("continueBtn").addEventListener("click", () => goToPanel("projects"));

/* ------------------------------------------------------------
   Account menu (top-right avatar)
   ------------------------------------------------------------
   The sidebar is reserved for learning/navigation; personal and
   account actions live in a compact menu anchored to the avatar.
   Reuses the shared .avatar-menu visual language from
   css/components/components.css.
   ------------------------------------------------------------ */
const ACCOUNT_ICONS = {
  profile: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
  settings: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/></svg>',
  logout: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5"/><path d="M21 12H9"/></svg>',
  moon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"/></svg>',
  sun: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>'
};

let dashAccountMenu = null;

function dashThemeIsDark() {
  return !!(window.LearnJS && window.LearnJS.theme && window.LearnJS.theme.isDark());
}
function dashThemeIcon() { return dashThemeIsDark() ? ACCOUNT_ICONS.sun : ACCOUNT_ICONS.moon; }
function dashThemeLabel() { return dashThemeIsDark() ? "Switch to light theme" : "Switch to dark theme"; }
function dashMenuItems() {
  return dashAccountMenu ? Array.from(dashAccountMenu.querySelectorAll(".avatar-menu-item")) : [];
}

function refreshDashThemeItem() {
  const item = dashAccountMenu && dashAccountMenu.querySelector('[data-account-action="theme"]');
  if (item) item.innerHTML = dashThemeIcon() + "<span>" + dashThemeLabel() + "</span>";
}

function openDashAccountMenu() {
  const menu = dashAccountMenu;
  const btn = el("dashAvatarBtn");
  if (!menu) return;
  refreshDashThemeItem();
  menu.hidden = false;
  btn.setAttribute("aria-expanded", "true");
  const items = dashMenuItems();
  if (items.length) items[0].focus();
}

function closeDashAccountMenu() {
  const menu = dashAccountMenu;
  const btn = el("dashAvatarBtn");
  if (!menu || menu.hidden) return;
  menu.hidden = true;
  btn.setAttribute("aria-expanded", "false");
  // Return focus to the avatar whenever it was inside the menu.
  if (menu.contains(document.activeElement)) btn.focus();
}

function buildAccountMenu(user) {
  const area = el("dashAccountArea");
  const btn = el("dashAvatarBtn");
  if (!area || !btn) return;

  const name = user.displayName || user.email || "Learner";
  const menu = document.createElement("div");
  menu.className = "avatar-menu dash-account-menu";
  menu.id = "dashAccountMenu";
  menu.setAttribute("role", "menu");
  menu.setAttribute("aria-label", "Account");
  menu.hidden = true;
  menu.innerHTML =
    '<div class="avatar-menu-head">' +
      '<span class="avatar avatar-sm av-green">' + initials(name) + "</span>" +
      '<div style="min-width:0">' +
        '<div class="avatar-menu-name">' + escapeHtml(name) + "</div>" +
        '<div class="avatar-menu-mail">' + escapeHtml(user.email || "") + "</div>" +
      "</div>" +
    "</div>" +
    '<button class="avatar-menu-item" type="button" role="menuitem" data-account-action="profile">' + ACCOUNT_ICONS.profile + "<span>View / Edit Profile</span></button>" +
    '<button class="avatar-menu-item" type="button" role="menuitem" data-account-action="settings">' + ACCOUNT_ICONS.settings + "<span>Account Settings</span></button>" +
    '<button class="avatar-menu-item" type="button" role="menuitem" data-account-action="theme">' + dashThemeIcon() + "<span>" + dashThemeLabel() + "</span></button>" +
    '<button class="avatar-menu-item danger" type="button" role="menuitem" data-account-action="logout">' + ACCOUNT_ICONS.logout + "<span>Logout</span></button>";
  area.appendChild(menu);
  dashAccountMenu = menu;

  btn.setAttribute("aria-haspopup", "menu");
  btn.setAttribute("aria-controls", "dashAccountMenu");

  // Toggle on avatar click (stopPropagation keeps the outside-click
  // listener below from immediately closing it).
  btn.addEventListener("click", (event) => {
    event.stopPropagation();
    if (menu.hidden) openDashAccountMenu();
    else closeDashAccountMenu();
  });

  // Item actions reuse the existing dashboard functionality: the profile
  // panel (with its edit modal), the settings panel, the shared theme
  // toggle and the existing logout flow (which flushes progress first).
  menu.addEventListener("click", (event) => {
    const item = event.target.closest("[data-account-action]");
    if (!item) return;
    const action = item.getAttribute("data-account-action");
    closeDashAccountMenu();
    if (action === "theme") {
      if (window.LearnJS && window.LearnJS.theme) window.LearnJS.theme.toggle();
    } else if (action === "profile") {
      goToPanel("profile");
    } else if (action === "settings") {
      goToPanel("settings");
    } else if (action === "logout") {
      logout();
    }
  });

  // Keyboard navigation inside the open menu (arrows / Home / End / Tab wrap).
  menu.addEventListener("keydown", (event) => {
    if (menu.hidden) return;
    const items = dashMenuItems();
    if (!items.length) return;
    const current = items.indexOf(document.activeElement);
    let next = -1;
    switch (event.key) {
      case "ArrowDown": next = current + 1 >= items.length ? 0 : current + 1; break;
      case "ArrowUp": next = current - 1 < 0 ? items.length - 1 : current - 1; break;
      case "Home": next = 0; break;
      case "End": next = items.length - 1; break;
      case "Tab":
        if (event.shiftKey && current <= 0) next = items.length - 1;
        else if (!event.shiftKey && current === items.length - 1) next = 0;
        else return; // normal tab movement within the menu
        break;
      default: return;
    }
    event.preventDefault();
    items[next].focus();
  });

  // Close when clicking anywhere outside the avatar + menu.
  document.addEventListener("click", (event) => {
    if (menu.hidden) return;
    const areaEl = el("dashAccountArea");
    if (areaEl && areaEl.contains(event.target)) return;
    closeDashAccountMenu();
  });
}

/* ---------- Roadmap module wiring ----------
   The roadmap and learning modules are event-driven so they stay
   decoupled from this page. "Start Learning" navigates to the
   dedicated Learning panel (never a popup); the breadcrumbs route
   back to the Roadmap / Home panels. */
window.addEventListener("learnjs:open-topic", (e) => {
  openTopic(e.detail && e.detail.topicId, (e.detail && e.detail.lessonIndex) || 0);
  goToPanel("learning");
});
window.addEventListener("learnjs:goto-roadmap", () => goToPanel("roadmap"));
window.addEventListener("learnjs:goto-home", () => goToPanel("home"));

/* ---------- Sidebar (mobile) ---------- */
function closeSidebar() { document.body.classList.remove("dash-open"); el("dashMenuToggle").setAttribute("aria-expanded", "false"); }
el("dashMenuToggle").addEventListener("click", () => {
  const open = document.body.classList.toggle("dash-open");
  el("dashMenuToggle").setAttribute("aria-expanded", String(open));
});
el("dashBackdrop").addEventListener("click", closeSidebar);

// Escape closes the account menu first, then the edit-profile modal
// (kept after the project modal was replaced by the details page).
document.addEventListener("keydown", (e) => {
  if (e.key !== "Escape") return;
  const menu = dashAccountMenu;
  if (menu && !menu.hidden) {
    closeDashAccountMenu();
    return;
  }
  const edit = el("editModal");
  if (edit && !edit.hidden) {
    edit.hidden = true;
    document.body.style.overflow = "";
  }
});

/* ---------- Filters ---------- */
["projectSearch", "categoryFilter", "difficultyFilter", "sortFilter"].forEach((id) => {
  const node = el(id);
  if (node) node.addEventListener("input", renderProjects);
});

// Populate category options dynamically from loaded data.
let lastCategories = "";
function refreshCategories() {
  const cats = [...new Set(allProjects.map((p) => p.category).filter(Boolean))].sort();
  const key = cats.join("|");
  if (key === lastCategories) return; // skip needless DOM churn on progress updates
  lastCategories = key;
  const select = el("categoryFilter");
  if (!select) return;
  const current = select.value;
  select.innerHTML = '<option value="all">All Categories</option>' +
    cats.map((c) => '<option value="' + escapeHtml(c) + '">' + escapeHtml(c) + "</option>").join("");
  if ([...select.options].some((o) => o.value === current)) select.value = current;
}

async function logout() {
  const btns = document.querySelectorAll("#dashLogout, #settingsLogoutBtn");
  btns.forEach((b) => { b.disabled = true; });
  toast("Saving progress…");

  // Flush any pending roadmap writes (incl. debounced notes) and wait for
  // them to settle before signing out / navigating away — never destroy the
  // page while a write is still in flight.
  try {
    flushPendingNotes();
    await flushWrites();
  } catch (err) {
    console.error("[LearnJS] Could not flush roadmap progress before logout:", err);
  }

  try {
    await signOut(auth);
    window.location.href = "../home/";
  } catch (err) {
    toast(err.message, "error");
    btns.forEach((b) => { b.disabled = false; });
  }
}
el("dashLogout").addEventListener("click", logout);
el("settingsLogoutBtn").addEventListener("click", logout);

/* ------------------------------------------------------------
   Roadmap sync banner + developer debug panel (dev only)
   ------------------------------------------------------------ */
function refreshRoadmapSyncBanner() {
  const banner = document.getElementById("roadmapSyncBanner");
  if (!banner) return;
  // Show only once a sync failure is known (never before we know either way).
  banner.hidden = getDebugInfo().syncHealthy !== false;
}

/**
 * The debug panel is NEVER part of the production DOM. It is built here, on
 * the fly, only when the explicit developer flag is enabled — so UID,
 * Firestore path, snapshot status, pending writes and other sync internals
 * cannot appear in production.
 */
function buildRoadmapDebugPanel() {
  const existing = document.getElementById("roadmapDebugPanel");
  if (existing) return existing;
  const panel = document.createElement("div");
  panel.className = "roadmap-debug-panel";
  panel.id = "roadmapDebugPanel";
  panel.innerHTML =
    '<div class="roadmap-debug-head">Roadmap Debug <span>DEV</span></div>' +
    '<dl class="roadmap-debug-grid">' +
      '<div><dt>UID</dt><dd id="rdbgUid">—</dd></div>' +
      '<div><dt>Firestore path</dt><dd id="rdbgPath">—</dd></div>' +
      '<div><dt>Snapshot</dt><dd id="rdbgSnapshot">—</dd></div>' +
      '<div><dt>Last sync</dt><dd id="rdbgLastSync">—</dd></div>' +
      '<div><dt>Pending writes</dt><dd id="rdbgPending">—</dd></div>' +
      '<div><dt>Completed topics</dt><dd id="rdbgTopics">—</dd></div>' +
      '<div><dt>Current level</dt><dd id="rdbgLevel">—</dd></div>' +
      '<div><dt>Current lesson</dt><dd id="rdbgLesson">—</dd></div>' +
    '</dl>';
  document.body.appendChild(panel);
  return panel;
}

function refreshRoadmapDebugPanel() {
  const info = getDebugInfo();
  const set = (id, value) => {
    const node = document.getElementById(id);
    if (node) node.textContent = value == null || value === "" ? "—" : String(value);
  };
  set("rdbgUid", info.uid);
  set("rdbgPath", info.path);
  set("rdbgSnapshot", info.snapshotStatus);
  set("rdbgLastSync", info.lastSyncTime ? new Date(info.lastSyncTime).toLocaleTimeString() : "—");
  set("rdbgPending", info.pendingWrites);
  set("rdbgTopics", info.completedTopics);
  set("rdbgLevel", info.currentLevel);
  set("rdbgLesson", info.currentLesson);
}

function initRoadmapDiagnostics() {
  // Offline banner stays production-safe (it only reflects sync health).
  refreshRoadmapSyncBanner();
  subscribeSync(refreshRoadmapSyncBanner);

  // Debug panel: ONLY when the explicit developer flag is enabled.
  if (!isDev()) return;
  const panel = buildRoadmapDebugPanel();
  panel.hidden = false;
  refreshRoadmapDebugPanel();
  subscribeSync(refreshRoadmapDebugPanel);
  subscribe(refreshRoadmapDebugPanel);
}

/* ------------------------------------------------------------
   Date helpers
   ------------------------------------------------------------ */
/** Millis from a Firestore Timestamp, Date, string or undefined. */
function tsMs(value) {
  if (!value) return 0;
  if (value.toMillis) return value.toMillis();
  const d = new Date(value).getTime();
  return isNaN(d) ? 0 : d;
}

function formatDate(value) {
  if (!value) return "\u2014";
  const d = value instanceof Date ? value : new Date(value);
  if (isNaN(d.getTime())) return "\u2014";
  return d.toLocaleDateString(undefined, { month: "short", year: "numeric" });
}

// end of dashboard.js
